### ISSUE TITLE
PrometheusRender should normalize `app_name`

### ISSUE THREAD

**Issue by gerowam** [jamesmistry/measuro#2]
Prometheus has some strict rules for characters allowed in the application name:

https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

Specifically:

> The metric name specifies the general feature of a system that is measured (e.g. http_requests_total - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.

The `PrometheusRenderer` constructor should either replace un-allowed characters, or throw when it finds them.

**Comment by jamesmistry** [comment]
The `PrometheusRenderer` constructor now throws an exception if the provided application name is invalid.
